Ready to use bot for btc/etc tickers
SkyForger79/shop_demo pull request #1
Opened 2018-07-14 22:17 UTC by SkyForger79

2018-07-15 21:23 UTC, bluzir requested changes
Нужно убрать лишний файл, а оставшийся переименовать в `main.py`, на крайняк `bot.py`

2018-07-15 21:23 UTC, bluzir commented on Bot#1.py
> +    url = "https://api.telegram.org/bot560754292:AAGQ3aTUK9p1LcUXuVPIZTiUewzGi1Kf5-4/getUpdates"
Выше же уже объявлен `url`, зачем дублировать

2018-07-15 21:23 UTC, bluzir commented on Bot#1.py
> +url = "https://api.telegram.org/bot560754292:AAGQ3aTUK9p1LcUXuVPIZTiUewzGi1Kf5-4/getMe"
Токен лучше спрятать в отдельный файл вне гита
И импортить оттуда, не забудь после этого перевыпустить старый токен

2018-07-15 21:23 UTC, bluzir commented on Bot#2.py
> +
что? откуда второй файл с кодом таким же
беру на ревью только первый

2018-07-15 21:23 UTC, bluzir commented on Bot#1.py
> +    url = "https://api.telegram.org/bot560754292:AAGQ3aTUK9p1LcUXuVPIZTiUewzGi1Kf5-4/getUpdates"
Для форматирования еще лучше использовать метод format
https://pythonworld.ru/osnovy/formatirovanie-strok-metod-format.html

2018-07-15 21:23 UTC, bluzir commented on Bot#1.py
> +    url = "https://api.telegram.org/bot560754292:AAGQ3aTUK9p1LcUXuVPIZTiUewzGi1Kf5-4/getUpdates"
url и токен только один раз в коде должны быть, а в остальным местах к нему подставляться должен

2018-07-15 21:23 UTC, bluzir commented on Bot#1.py
> +responce = requests.get(url)
Это все мы использовали для тестов, в итоговой версии не должно быть кода, который не используется, эти 10 строк до функции можно смело удалять

2018-07-15 21:24 UTC, bluzir commented
Задание при этом далеко не сделано, даже отправки сообщений нет — это плохо

2018-07-16 23:47 UTC, SkyForger79 commented on Bot#1.py
> +    url = "https://api.telegram.org/bot560754292:AAGQ3aTUK9p1LcUXuVPIZTiUewzGi1Kf5-4/getUpdates"
Не тот файл. Этот файл был тестовым, на базе которого проходил занятия.

2018-07-16 23:47 UTC, SkyForger79 commented on Bot#1.py
> +url = "https://api.telegram.org/bot560754292:AAGQ3aTUK9p1LcUXuVPIZTiUewzGi1Kf5-4/getMe"
Ок. Я поправлю.

2018-07-16 23:48 UTC, SkyForger79 commented on Bot#2.py
> +
Это как раз правильный файл. В нем домашка сделана. Бот делает все, что нужно:
- Запрашивает апдейты
- Следит за командами
- Запрашивает котировки

2018-07-16 23:50 UTC, SkyForger79 commented
И что теперь делать?
Переименовать файлы и снова запросить?

2018-07-17 00:00 UTC, SkyForger79 commented on Bot#2.py
> +
Блин, похоже последние изменения не сохранились ((, очень странно. Я могу скрины прислать, что бот работал
![image](https://user-images.githubusercontent.com/29904499/42789345-8792fb2c-896d-11e8-849f-4f96065d17e6.png)

2018-07-24 12:50 UTC, merged